spring.application.name=eleave-management-backend

spring.datasource.url=jdbc:mysql://localhost:3306/eleave_db
spring.datasource.username=root
spring.datasource.password=Samiru111036

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


